### ISSUE TITLE
El logo en fechas no se ve bien

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/enflujo-www#34]
<img width="306" alt="Captura de Pantalla 2022-06-01 a la(s) 11 51 13 a m" src="https://user-images.githubusercontent.com/4657617/171458420-62e1b439-2c67-41eb-8ddd-e95be436c64d.png">

El tamaño es aproximadamente 13x13 pixeles y ahí siento que no se ve tan bien.

El anterior creo que si funcionaba mejor, lo dejo acá de referencia.
<img width="305" alt="Captura de Pantalla 2022-06-01 a la(s) 11 53 40 a m" src="https://user-images.githubusercontent.com/4657617/171458949-39745b99-d2b9-4ffb-b9e0-d9d5f4fd4d47.png">

**Comment by HoyosQ** [comment]
Estuve probando alternativas con el inspector pero creo que tocaria ajustar el tamaño del font tambien para que el logo no se vea fuera de lugar. Probe con 15 x 15 pixeles, 20 x 20 pixeles y 25 x 25 pixeles. Adjunto imagenes. 

![Image](https://user-images.githubusercontent.com/89080958/218286346-deb0e92d-8905-47f7-a445-351db841edc1.png)

15 x 15

![Image](https://user-images.githubusercontent.com/89080958/218286353-6a498ca8-ab64-4c31-a201-a7024563bfad.png)

20 x 20


![Image](https://user-images.githubusercontent.com/89080958/218286368-e3c17f3d-e92c-418a-b6bd-b23ba8afd3f8.png)

 
25 x 25

**Comment by 1cgonza** [comment]
@HoyosQ este problema parece resuelto pues el icono que no funcionaba por ser de línea muy delgada ya se cambió por uno más sólido que funciona pequeño. Dejo que @Juliansintilde revise para ver si usamos este de la lista de diseños y qué tamaño debería tener.
