### ISSUE TITLE
📩 Llamado de dato errado del directus

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/enflujo-www#66]
En la página de los perfiles el cargo se está llamando desde la casilla para máquinas y no la casillla para humanos:

<img width="952" alt="image" src="https://github.com/user-attachments/assets/57e0abcc-8a4b-4e23-bd46-90a5f6da2e14">

<img width="239" alt="image" src="https://github.com/user-attachments/assets/3ce4fa10-684b-41d5-b966-fa1ac81c045e">

**Comment by 1cgonza** [comment]
Resuelto desde el CMS, Texto y Valor deben ser iguales.
