### ISSUE TITLE
📸 Quitar opción de cambiar la imagen predeterminada sinFoto en api

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/enflujo-www#67]
Cuando se está en la api de enflujo, en la interfaz de creación o modificación de perfil en el equipo, debemos deshabilitar la opción de cambio de foto, porque conduce a cambiar la imagen "sinFoto".

<img width="408" alt="image" src="https://github.com/user-attachments/assets/a4d18518-84f9-4f0e-a083-92ecc9f5510e">

Lo mejor sería que de entrada pida una imagen, para que no modifique la anterior.
La imagen por defecto "sinFoto.png" se puede llamar directamente desde el código cuando no encuentre otra.

<img width="421" alt="image" src="https://github.com/user-attachments/assets/9d2d7da8-7e5c-4af0-9897-759f588f5f84">

**Comment by 1cgonza** [comment]
Resuelto
