### ISSUE TITLE
:sob: PATALETA

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/enflujo-www#74]
Esto es una pataleta a grito herido.

@Juliansintilde @jesusparedesg y @lauechev no tienen en sus perfiles de Github el vínculo con EnFlujo, les da pena que lo vea la gente, no nos quieren, somos una porquería. 

![Screenshot from 2024-10-18 08-12-47](https://github.com/user-attachments/assets/25b34565-a036-4330-9d32-34e6a44e179d)

Y en sus perfiles no se ve NADAAAAAAA, bueno @Juliansintilde puso ahí en su biografía que hace cosas en EnFlujo pero igual :crying_cat_face: 

![Screenshot from 2024-10-18 08-13-46](https://github.com/user-attachments/assets/4e03a5c8-80b2-4ccb-b17f-128449dd7d01)

Cuando lo ponen público se ve así (toca probar en incógnito para ver como lo ve la otra gente):

![Screenshot from 2024-10-18 08-14-15](https://github.com/user-attachments/assets/4760659f-a9ed-4382-bdf1-64692c10c44f)

Ademásssss...es muy triste que @lauechev y @jesusparedesg no tienen imagen de perfil sino que dejaron el icono ese picho que pone Github....triste todo.

... fin del berrinche ... :heart_hands:

**Comment by lauechev** [comment]
jajajaj ya solucionado todo de mi lado!! con enflujo en el perifl y foto nueva

**Comment by Juliansintilde** [comment]
solucionado por este lado gracias a la ayuda de @lauechev hacker
